import { ArrowUpRight, Broadcast, CheckCircle, Plus } from "@phosphor-icons/react";
import type { Channel, Task } from "@studio/shared";
import { formatTaskElapsed, formatTaskType, isTaskActive } from "../lib/utils";
import { EmptyState } from "./EmptyState";
import { PageTitle } from "./AppChrome";

export function ChannelCard({ channel, index, onOpen }: { channel: Channel; index: number; onOpen: () => void }) { return <button className="channel-card" onClick={onOpen}><div className="card-top"><div className="card-identity"><span className="channel-index">{String(index).padStart(2, "0")}</span><div className="channel-avatar">{channel.display_name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "CH"}</div></div><span className={`status-badge ${channel.status.toLowerCase()}`}>{channel.status.toLowerCase()}</span></div><h3>{channel.display_name}</h3><p>{channel.description || "Channel DNA ready."}</p><div className="card-bottom"><span>{channel.episode_count} {channel.episode_count === 1 ? "episode" : "episodes"}</span><ArrowUpRight size={16} /></div></button>; }

function Metric({ label, value, note }: { label: string; value: number; note: string }) { return <div className="metric"><span className="metric-label">{label}</span><strong>{value}</strong><span className="metric-note">{note}</span></div>; }
function TaskRow({ task, now }: { task: Task; now: number }) { return <div className={`activity-row ${isTaskActive(task) ? "is-processing" : ""}`}><div className={`task-status-dot ${task.status.toLowerCase()}`} /><div><strong>{formatTaskType(task.task_type)}</strong><span>{task.error || task.progress_message || task.status}</span></div><span className="task-elapsed">{formatTaskElapsed(task, now)}</span><span className="activity-status">{task.status}</span></div>; }

export function DashboardView({ channels, tasks, activeTasks, now, onCreate, openChannel, openTaskList }: { channels: Channel[]; tasks: Task[]; activeTasks: Task[]; now: number; onCreate: () => void; openChannel: (id: string) => void; openTaskList: () => void }) {
  const reviewCount = tasks.filter((task) => task.status === "WAITING_APPROVAL").length;
  const completedCount = tasks.filter((task) => task.status === "COMPLETED").length;
  return <section className="page-wrap"><div className="hero-row"><div><p className="eyebrow">Workspace</p><h1>Dashboard</h1></div><button className="primary-button hero-action" onClick={onCreate}><Plus size={18} />New channel</button></div><div className="metric-grid"><Metric label="Channels" value={channels.length} note="Total" /><Metric label="Episodes" value={channels.reduce((total, channel) => total + channel.episode_count, 0)} note="Confirmed" /><Metric label="Running" value={activeTasks.length} note="Tasks" /><Metric label="Review" value={reviewCount} note={reviewCount ? "Required" : `${completedCount} done`} /></div><div className="section-heading"><div><p className="eyebrow">Library</p><h2>Channels</h2></div></div>{channels.length === 0 ? <EmptyState icon={<Broadcast size={26} />} title="No channels" copy="Create a channel to begin." action="Create channel" onAction={onCreate} /> : <div className="channel-grid">{channels.map((channel, index) => <ChannelCard key={channel.channel_id} index={index + 1} channel={channel} onOpen={() => openChannel(channel.channel_id)} />)}</div>}<div className="section-heading activity-heading"><div><p className="eyebrow">Tasks</p><h2>Recent activity</h2></div><button className="text-button" onClick={openTaskList}>View all <ArrowUpRight size={15} /></button></div>{tasks.length === 0 ? <div className="activity-empty"><CheckCircle size={19} />No tasks yet.</div> : <div className="activity-list">{tasks.slice(0, 4).map((task) => <TaskRow key={task.task_id} task={task} now={now} />)}</div>}</section>;
}

export function ChannelsListView({ channels, onCreate, openChannel }: { channels: Channel[]; onCreate: () => void; openChannel: (id: string) => void }) { return <section className="page-wrap"><PageTitle eyebrow="Library" title="Channels" action={<button className="primary-button" onClick={onCreate}><Plus size={17} />New channel</button>} />{channels.length === 0 ? <EmptyState icon={<Broadcast size={26} />} title="No channels yet" copy="Create a channel to begin." action="Create channel" onAction={onCreate} /> : <div className="channel-grid channel-grid-wide">{channels.map((channel, index) => <ChannelCard key={channel.channel_id} index={index + 1} channel={channel} onOpen={() => openChannel(channel.channel_id)} />)}</div>}</section>; }
